[package]
name = "crates"
version = "0.1.0"
edition = "2021"

[lib]
name = "crates"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.38"
pyo3 = { version = "0.18", features = ["abi3-py311", "extension-module"] }
walkdir = "2.5.0"
