# coding: utf-8

"""empty message

Revision ID: 17f96fb856ef
Revises: None
Create Date: 2014-08-28 13:03:29.209992

"""

# revision identifiers, used by Alembic.
revision = '17f96fb856ef'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whisky',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distillery', sa.String(length=64), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Integer(), nullable=True),
    sa.Column('sweetness', sa.Integer(), nullable=True),
    sa.Column('smoky', sa.Integer(), nullable=True),
    sa.Column('medicinal', sa.Integer(), nullable=True),
    sa.Column('tobacco', sa.Integer(), nullable=True),
    sa.Column('honey', sa.Integer(), nullable=True),
    sa.Column('spicy', sa.Integer(), nullable=True),
    sa.Column('winey', sa.Integer(), nullable=True),
    sa.Column('nutty', sa.Integer(), nullable=True),
    sa.Column('malty', sa.Integer(), nullable=True),
    sa.Column('fruity', sa.Integer(), nullable=True),
    sa.Column('floral', sa.Integer(), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_whisky_distillery', 'whisky', ['distillery'], unique=True)
    op.create_index(u'ix_whisky_slug', 'whisky', ['slug'], unique=True)
    op.create_table('correlation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.Integer(), nullable=True),
    sa.Column('whisky', sa.Integer(), nullable=True),
    sa.Column('r', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['whisky'], ['whisky.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(u'ix_correlation_r', 'correlation', ['r'], unique=False)
    op.create_index(u'ix_correlation_reference', 'correlation', ['reference'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_correlation_reference', table_name='correlation')
    op.drop_index(u'ix_correlation_r', table_name='correlation')
    op.drop_table('correlation')
    op.drop_index(u'ix_whisky_slug', table_name='whisky')
    op.drop_index(u'ix_whisky_distillery', table_name='whisky')
    op.drop_table('whisky')
    ### end Alembic commands ###
