"""Add views to Whisky model

Revision ID: 1a00deb0edba
Revises: 4cbf0230c35
Create Date: 2014-12-19 14:51:37.865571

"""

# revision identifiers, used by Alembic.
revision = '1a00deb0edba'
down_revision = '4cbf0230c35'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whisky', sa.Column('views', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whisky', 'views')
    ### end Alembic commands ###
