"""Drops views column

Revision ID: 4891a73e96a5
Revises: 447b2802474f
Create Date: 2024-04-26 13:07:15.175252

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4891a73e96a5"
down_revision = "447b2802474f"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("whisky", "views")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("whisky", sa.Column("views", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
